name: blue_print_pos
description: Plugin to connecting bluetooth printer device, support on Android and iOS
version: 1.0.2
homepage: https://github.com/iandis/blue_print_pos

publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  # Utilities for generate ByteBuffer
  esc_pos_utils_plus: ^2.0.1+6
  fluetooth:
    git:
      url: https://github.com/youtaplibrary/fluetooth.git
      ref: 0.1.2
  # Framework
  flutter:
    sdk: flutter
  # Image utilities
  image: ^3.1.3
  # Generate qr image painter
  qr_flutter:
    git: https://github.com/theyakka/qr.flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ayeee.blue_print_pos
        pluginClass: BluePrintPosPlugin
      ios:
        pluginClass: BluePrintPosPlugin
